name: fcp-audit

services:
  fcp-audit:
    ports:
      - '3004:3004'
    networks:
      - fcp-audit

  mongodb:
    ports:
      - '27018:27017'
    networks:
      - fcp-audit
    volumes:
      - mongodb-data:/data

  floci:
    ports:
      - '4567:4566'
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-audit

  floci-init:
    networks:
      - fcp-audit

  fcp-audit-publisher-stub:
    ports:
      - '3005:3005'
    networks:
      - fcp-audit

networks:
  fcp-audit:
    driver: bridge
    name: fcp-audit

volumes:
  mongodb-data:
  floci-data:
